ecommerce/cart/urls.py
from django.urls import path
from cart.views import AddToCart,CartListView,CartDeleteView,CartQtyChangeView,CheckoutCart
app_name='cart'
urlpatterns = [
   path('<int:productid>',AddToCart.as_view(),name='addcart'),
   path('list',CartListView.as_view(),name='list'),
   path('deletecart/<int:cart_item_id>',CartDeleteView.as_view(),name='delete_cart'),
   path('updatecart',CartQtyChangeView.as_view(),name='update_cart'),
   path('checkout',CheckoutCart.as_view(),name='checkout'),
]

ecommerce/custadmin/urls.py
from django.urls import path
from .views import *
from product.views import *
app_name='custadmin'
urlpatterns = [
    path('',AdminDashboard.as_view(),name='admin_dashboard'),
    #category

    path('category/',CategoryListView.as_view(),name='category_list'),
    path('category/create',CategoryCreateView.as_view(),name='category_create'),
    path('category/update/<str:slug>', CategoryUpdateView.as_view(),name='category_update'),
    path('category/delete/<str:slug>', CategoryDeleteView.as_view(),name='category_delete'),
    
    #brand
    path('brand/',BrandListView.as_view(),name='brand_list'),
    path('brand/create',BrandCreateView.as_view(),name='brand_create'),
    path('brand/update/<str:slug>',BrandUpdateView.as_view(), name='brand_update'),
    path('brand/delete/<str:slug>',BrandDeleteView.as_view(), name='brand_delete'),

    #product
    path('product/create',ProductCreateView.as_view(),name='product_create'),
    path('product/',ProductAdminListView.as_view(),name="product_list"),
    path('product/update/<str:slug>',ProductUpdateView.as_view(),name='product_update'),

     #coupon
    path('coupon/',CouponListView.as_view(),name='coupon_list'),
    path('coupon/create',CouponCreateView.as_view(),name='coupon_create'),
    path('coupon/update/<int:pk>',CouponUpdateView.as_view(), name='coupon_update'),
    path('coupon/delete/<int:pk>',CouponDeleteView.as_view(), name='coupon_delete'),


   path('home',AdminDashboard.as_view(),name="dashboard"),
    path('user',UserListView.as_view(),name="user"),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import LogoutView
urlpatterns = [
    path('django/admin/', admin.site.urls),
    path('admin/',include('custadmin.urls')),
    path("",include(('user.urls','user'),namespace='user')),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("cart/",include(('cart.urls','cart'),namespace='cart')),
    path("order/",include(('order.urls','order'),namespace='order')),
    path("product/",include(('product.urls','product'),namespace='product')),


]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

ecommerce/base/views.py
from django.contrib.auth.views import LoginView,LogoutView
from django.views.generic.list  import ListView
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView,DeleteView,CreateView
from django.views.generic.detail import DetailView
from django.views.generic.base import RedirectView
class BaseListView(ListView):
    pass
class BaseTemplateView(TemplateView):
    pass

class BaseUpdateView(UpdateView):
    pass

class BaseDeleteView(DeleteView):
    pass
class BaseCreateView(CreateView):
    pass
class BaseLoginView(LoginView):
    pass

class BaseDetailView(DetailView): 
    pass

class BaseRedirectView(RedirectView):
    pass

ecommerce/templates/adminportol/brand_create.html
{% extends "adminportol/base.html" %}
{% load crispy_forms_tags %}
{% block container %}
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

{% include "adminportol/navbar.html" %}
{% include "adminportol/sidebar.html" %}
  <div class="content-wrapper">
    <div class="content">
      <div class="container-fluid">
          <div class="card card-info">
            <div class="card-header">
              <h3 class="card-title">Brand</h3>
            </div>
            <form class="form-horizontal" method="post">
                {% csrf_token %}
              <div class="card-body">
                <div class="form-group row">

                  <div class="col-sm-12">
                    {{form.name|as_crispy_field}}
                  </div>
                </div>
              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                <button type="submit" class="btn btn-info">Create</button>
              </div>
              <!-- /.card-footer -->
            </form>
          </div>
          <!-- /.card -->


        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
</div>
  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
  {% endblock  %}

ecommerce/templates/adminportol/brand_list.html
{% extends "adminportol/base.html" %}
{% block container %}
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
  <!-- Navbar -->
{% include "adminportol/navbar.html" %}
  <!-- /.navbar -->
  <!-- Main Sidebar Container -->
{% include "adminportol/sidebar.html" %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0"><a href="{% url 'custadmin:brand_create' %}">Add Brand</a></h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Brand</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="card">
            <div class="card-header">
              <h3 class="card-title">Brands</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
           <table id="example1" class="table table-bordered table-striped display">
                <thead>
                <tr>
                  <th>Name</th>
                  <th>Slug</th>
                  <th>Edit</th>
                  <th>Delete</th>
                  
                </tr>
                </thead>
                <tbody>
                {% for brand in brands %}
                <tr>

                  <td>{{brand.name}}</td>
                  <td>{{brand.slug}}</td>
                  <td><a href="{% url 'custadmin:brand_update' brand.slug %}"><i class="fas fa-pen"></i></a> </td>
                    <form method="post" action="{% url 'custadmin:brand_delete' brand.slug %}">
                        {% csrf_token %}
                        <td>
                          <button type="submit" class="btn btn-primary">
  <i class="fas fa-trash"></i> </button>

                        </td>
                      
                    </form>
                </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    <th>Name</th>
                    <th>Slug</th>
                  <th>Action</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
  {% endblock %}
{% block js %}

{% endblock js %}

ecommerce/templates/adminportol/brand_update.html
{% extends "adminportol/base.html" %}
{% load crispy_forms_tags %}
{% block container %}
<body class="hold-transition sidebar-mini layout-fixed ">
<div class="wrapper">
  <!-- Navbar -->
{% include "adminportol/navbar.html" %}
  <!-- /.navbar -->
  <!-- Main Sidebar Container -->
{% include "adminportol/sidebar.html" %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="card">
            <div class="card-header">
              <h3 class="card-title">Brands</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <form class="form-horizontal" method="post">
                {% csrf_token %}
              <div class="card-body">
                <div class="form-group row">

                  <div class="col-sm-12">
                    {{form.name|as_crispy_field}}
                  </div>
                </div>
              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                <button type="submit" class="btn btn-info">Update</button>
              </div>
              <!-- /.card-footer -->
            </form>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
  {% endblock %}

ecommerce/templates/adminportol/category_list.html
{% extends "adminportol/base.html" %}
{% block container %}
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
  <!-- Navbar -->
{% include "adminportol/navbar.html" %}
  <!-- /.navbar -->
  <!-- Main Sidebar Container -->
{% include "adminportol/sidebar.html" %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0"><a href="{% url 'custadmin:category_create' %}">Add Category</a></h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Cateory</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>

    <div class="content">
      <div class="container-fluid">
        <div class="card">
            <div class="card-header">
              <h3 class="card-title">Cateory</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-bordered">
                <thead>
                <tr>
                  <th>Name</th>
                  <th>Slug</th>
                  <th>parent</th>
                  <th>Edit</th>
                  <th>Delete</th>

                </tr>
                </thead>
                <tbody>
                {% for cateory in cateories %}
                <tr>

                  <td>{{cateory.name}}</td>
                  <td>{{cateory.slug}}</td>
                  <td>{{cateory.parent}}</td>
                  <td><a href="{% url 'custadmin:category_update' cateory.slug %}">Edit</a> </td>
                    <form method="post" action="{% url 'custadmin:category_delete' cateory.slug %}">
                        {% csrf_token %}
                  <td> <input type="submit" value="Delete"></td>
                    </form>
                </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    <th>Name</th>
                    <th>Slug</th>
                    <th>parent</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </div>
  </div>
  <aside class="control-sidebar control-sidebar-dark">
  </aside>
  {% endblock %}
{% block js %}

{% endblock js %}

ecommerce/templates/adminportol/coupon_create.html
{% extends "adminportol/base.html" %}
{% load crispy_forms_tags %}
{% block container %}
<body class="hold-transition sidebar-mini">
<div class="wrapper">
  <!-- Navbar -->
{% include "adminportol/navbar.html" %}
  <!-- /.navbar -->
  <!-- Main Sidebar Container -->
{% include "adminportol/sidebar.html" %}

  <div class="content-wrapper">
    <div class="content">
      <div class="container-fluid">
          <!-- Horizontal Form -->
          <div class="card card-info">
            <div class="card-header">
              <h3 class="card-title">Coupon</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form class="form-horizontal" method="post">
                {% csrf_token %}
              <div class="card-body">
                <div class="form-group row">

                  <div class="col-sm-12">
                    {{form|crispy}}
                  </div>
                </div>
              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                <button type="submit" class="btn btn-info">Create</button>
              </div>
              <!-- /.card-footer -->
            </form>
          </div>
          <!-- /.card -->

        
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
</div>
  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
  {% endblock  %}

ecommerce/templates/adminportol/dashboard.html
{% extends  "adminportol/base.html" %}
{% load crispy_forms_tags %}
{% block container %}
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
  <!-- Navbar -->
{% include "adminportol/navbar.html" %}
  <!-- /.navbar -->
  <!-- Main Sidebar Container -->
{% include "adminportol/sidebar.html" %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->

    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
          <!-- Horizontal Form -->
       
        
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
</div>
  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
  {% endblock  %}

ecommerce/templates/adminportol/formset_specification.html
{% load static %}
{% load crispy_forms_tags %}
<table>
{{ formset.management_form|crispy }}

    {% for form in formset.forms %}
            <tr class="{% cycle 'row1' 'row2' %} formset_row-{{ formset.prefix }}">
                {% for field in form.visible_fields %}
                <td>
                    {# Include the hidden fields in the form #}
                    {% if forloop.first %}
                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                    {% endif %}
                    {{ field.errors.as_ul }}
                    {{ field|as_crispy_field }}
                </td>
                {% endfor %}
            </tr>
    {% endfor %}

</table>
<br>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js">
</script>
<script src="{% static 'adminpotol/jquery.formset.js' %}">
</script>
<script type="text/javascript">
    $('.formset_row-{{ formset.prefix }}').formset({
        addText: 'add another',
        deleteText: 'remove',
        prefix: '{{ formset.prefix }}',
    });
</script>

ecommerce/templates/adminportol/index.html
{% extends "adminportol/base.html" %}
{% block container %}
<body class="hold-transition sidebar-mini">
<div class="wrapper">
  <!-- Navbar -->
{% include "adminportol/navbar.html" %}
  <!-- /.navbar -->
  <!-- Main Sidebar Container -->
{% include "adminportol/sidebar.html" %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Dashboard v3</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        
        
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
  {% endblock %}

ecommerce/templates/adminportol/invoice.html
{% extends "adminportol/base.html" %}
{% block container %}
{% load static %}
<body class="hold-transition sidebar-mini">
<div class="wrapper">
    {% include "adminportol/navbar.html" %}
  
    {% include "adminportol/sidebar.html" %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->


    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">


            <!-- Main content -->
            <div class="invoice p-3 mb-3">
              <!-- title row -->
              <div class="row">
                <div class="col-12">
                  <h4>
                    <i class="fas fa-globe"></i> 
                    <small class="float-right">Date: {{order.created}}</small>
                  </h4>
                </div>
                <!-- /.col -->
              </div>
              <!-- info row -->
              <div class="row invoice-info">
                <div class="col-sm-4 invoice-col">
                  From
                  <address>
                    <strong>Admin, Inc.</strong><br>
                    795 Folsom Ave, Suite 600<br>
                    San Francisco, CA 94107<br>
                    Phone: (804) 123-5432<br>
                    Email: info@almasaeedstudio.com
                  </address>
                </div>
                <!-- /.col -->
                <div class="col-sm-4 invoice-col">
                  To
                  <address>
                    <strong>{{order.user.first_name}}</strong><br>
                    {{order.address}} {{order.address.city}}<br>
                    {{order.address.state}} {{order.address.state}}<br>
                    {{order.address.zipcode}}<br>
                    Email: {{order.user}}
                  </address>
                </div>
                <!-- /.col -->
                <!-- /.col -->
                <div class="col-sm-4 invoice-col">
                  <b>Invoice #00{{order.pk}}</b><br>
                  <br>
                  <b>Order ID:</b> 4F{{order.pk}}<br>
           
                </div>
                <!-- /.col -->
              </div>
              <!-- /.row -->

              <!-- Table row -->
              <div class="row">
                <div class="col-12 table-responsive">
                  <table class="table table-striped">
                    <thead>
                    <tr>
                      <th>Qty</th>
                      <th>Product</th>
                      <th>Category</th>
                      <th>Brand</th>
                      <th>Product Price</th>
                      <th>Subtotal</th>
                    </tr>
                    </thead>
                    {% for order in orderitem %}
                    <tbody>
                    <tr>
                      <td> {{order.qty}}  </td>
                      <td> {{order.product}} </td>
                      <td> {{order.product.category}} </td>
                      <td> {{order.product.brand}} </td>
                      <td> Rs.{{order.product.price}} </td>
                      <td> RS.{{order.price}}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                  </table>
                </div>
                <!-- /.col -->
              </div>
              <!-- /.row -->

              <div class="row">
                <!-- accepted payments column -->
                <div class="col-6">
                  <p class="lead">Payment Methods:</p>
                  <img src="{% static 'adminpotol/dist/img/credit/visa.png'%}" alt="Visa">
                  <img src="{% static 'adminpotol/dist/img/credit/mastercard.png'%}" alt="Mastercard">
                  <img src="{% static 'adminpotol/dist/img/credit/american-express.png'%}" alt="American Express">
                  <img src="{% static 'adminpotol/dist/img/credit/paypal2.png'%}" alt="Paypal">

                  <p class="text-muted well well-sm shadow-none" style="margin-top: 10px;">
                
                  </p>
                </div>
                <!-- /.col -->
                <div class="col-6">
                  <div class="table-responsive">
                    <table class="table">
                      <tr>
                        <th style="width:50%">Subtotal:</th>
                        <td>RS : {{order.total_amount}}</td>
                      </tr>

                      <tr>
                        <th>Shipping:</th>
                        <td>Rs:0.0</td>
                      </tr>
                      <tr>
                        <th>Total:</th>
                        <td>RS : {{order.total_amount}}</td>
                      </tr>
                    </table>
                  </div>
                </div>
                <!-- /.col -->
              </div>
              <!-- /.row -->

              <!-- this row will not appear when printing -->
              <div class="row no-print">
                <div class="col-12">
                  <a href="invoice-print.html" rel="noopener" target="_blank" class="btn btn-default"><i class="fas fa-print"></i> Print</a>
                  <button type="button" class="btn btn-primary float-right" style="margin-right: 5px;">
                    <i class="fas fa-download"></i> Generate PDF
                  </button>
                </div>
              </div>
            </div>
            <!-- /.invoice -->
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->
{% endblock %}

ecommerce/templates/adminportol/navbar.html
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>


  </nav>
  <!-- /.navbar -->

ecommerce/templates/adminportol/order_status_update.html
{% extends "adminportol/base.html" %}
{% load crispy_forms_tags %}
{% block container %}
<body class="hold-transition sidebar-mini layout-fixed ">
<div class="wrapper">
  <!-- Navbar -->
{% include "adminportol/navbar.html" %}
  <!-- /.navbar -->
  <!-- Main Sidebar Container -->
{% include "adminportol/sidebar.html" %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="card">
            <div class="card-header">
              <h3 class="card-title">Order</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <form class="form-horizontal" method="post">
                {% csrf_token %}
              <div class="card-body">
                <div class="form-group row">

                  <div class="col-sm-12">
                    {{form|crispy}}
                  </div>
                </div>
              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                <button type="submit" class="btn btn-info">Update</button>
              </div>
              <!-- /.card-footer -->
            </form>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
  {% endblock %}

ecommerce/templates/adminportol/product_list.html
{% extends "adminportol/base.html" %}
{% block container %}
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
  <!-- Navbar -->
{% include "adminportol/navbar.html" %}
  <!-- /.navbar -->
  <!-- Main Sidebar Container -->
{% include "adminportol/sidebar.html" %}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0"><a href="{% url 'custadmin:product_create' %}">Add Product</a></h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Product</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="card">
            <div class="card-header">
              <h3 class="card-title">Product</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped display">
                <thead>
                <tr>
                  <th>Image</th>
                  <th>Name</th>
                  <th>Price</th>
                  <th>Available</th>
                  <th>Category</th>
                  <th>Brand</th>
                  <th>Edit</th>

                  <th>Delete</th>
                </tr>
                </thead>
                <tbody>
                {% for product in products%}
                <tr>
                  <td><img src="{{product.images.all.first}}" width="50px" height="50px"></td>
                  <td>{{product.name}}</td>
                  <td>RS.{{product.price}}</td>
                  {% if product.status == 1%}
                  <td>True</td>
                  {% else %}
                  <td>False</td>
                  {% endif %}
                  <td>{{product.category}}</td>
                  <td>{{product.brand}}</td>
                  <td><a href="{% url 'custadmin:product_update' product.slug %}">Edit</a></td>
                  <td>Delete</td>
                </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>

                  <th>Image</th>
                  <th>Name</th>
                  <th>Price</th>
                  <th>Available</th>
                  <th>Category</th>
                  <th>Brand</th>
                  <th>Edit</th>
                  <th>Delete</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
  {% endblock %}
{% block js %}
<script>
  $(document).ready(function() {
    $('table.display').( {
    responsive: true
} );
</script>
{% endblock js %}