ecommerce/cart/urls.py
from django.urls import path
from cart.views import AddToCart,CartListView,CartDeleteView,CartQtyChangeView,CheckoutCart
app_name='cart'
urlpatterns = [
   path('<int:productid>',AddToCart.as_view(),name='addcart'),
   path('list',CartListView.as_view(),name='list'),
   path('deletecart/<int:cart_item_id>',CartDeleteView.as_view(),name='delete_cart'),
   path('updatecart',CartQtyChangeView.as_view(),name='update_cart'),
   path('checkout',CheckoutCart.as_view(),name='checkout'),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import LogoutView
urlpatterns = [
    path('django/admin/', admin.site.urls),
    path('admin/',include('custadmin.urls')),
    path("",include(('user.urls','user'),namespace='user')),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("cart/",include(('cart.urls','cart'),namespace='cart')),
    path("order/",include(('order.urls','order'),namespace='order')),
    path("product/",include(('product.urls','product'),namespace='product')),


]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

ecommerce/order/urls.py
from django.urls import path
from .views import AdminOrderDetailView, AdminOrderListView, OrderStatusUpdateView, PlaceorderView,OrderListView,OrderDetailView
app_name='order'
urlpatterns = [
    path('placeorder/', PlaceorderView.as_view(),name='placeorder'),
    path('list/',OrderListView.as_view(),name='order_lists'),
    path('view/<int:pk>',OrderDetailView.as_view(),name='order_details'),
    path('orderlist/',AdminOrderListView.as_view(),name='order_admin_list'),
    path('orderdetails/<int:pk>',AdminOrderDetailView.as_view(),name='order_admin_details'),
    path('status/update/<int:pk>',OrderStatusUpdateView.as_view(),name='order_status_update'),
  ]

ecommerce/product/urls.py
from django import urls
from django.urls import path

from .views import *

app_name = 'product'
urlpatterns = [
    path('<pk>', ProdectDetailView.as_view(), name='product_details'),
]



ecommerce/user/urls.py
from .views import *
from django.urls import path, include
from product.views import DashboardTemplateView, ProductListView

app_name = 'user'
urlpatterns = [
    path('login/', LoginView.as_view(), name="login"),
    path("signup/", SignupView.as_view(), name="signup"),
    path("", DashboardTemplateView.as_view(), name="dashboard"),
    path("category/", ProductListView.as_view(), name="category"),
    path('wishlist/<int:productid>', WishlistCreateview.as_view(), name='wishlist_create'),
    path('wishlist/', WishlistListView.as_view(), name='wishlist'),
    path('wistlist/delete/<int:pk>', WishlistDeleteView.as_view(), name='wishlist_delete'),
    path('profile/<int:pk>', UserProfileUpdateView.as_view(), name='profile'),
    path('password/change/ ', PasswordChangeView.as_view(), name="change_password"),
    path('address/create',UserAddressCreateView.as_view(),name='create_address'),
    path('address/delete/<int:pk>',UserAddressDeleteview.as_view(),name='address_delete'),
    path('address/update/<int:pk>',UserAddressUpdateview.as_view(),name='address_update'),

]

ecommerce/cart/models.py
from django.db import models
from user.models import User
from product.models import Product
from base.base import BaseModel
from django_extensions.db.models import *


# Create your models here.
class Cart(TimeStampedModel, models.Model):
    user = models.ForeignKey(User, related_name='users', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='products', on_delete=models.CASCADE)
    qty = models.IntegerField(default=1)

    @property
    def total_amount(self):
        return self.qty * self.product.price

ecommerce/base/views.py
from django.contrib.auth.views import LoginView,LogoutView
from django.views.generic.list  import ListView
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView,DeleteView,CreateView
from django.views.generic.detail import DetailView
from django.views.generic.base import RedirectView
class BaseListView(ListView):
    pass
class BaseTemplateView(TemplateView):
    pass

class BaseUpdateView(UpdateView):
    pass

class BaseDeleteView(DeleteView):
    pass
class BaseCreateView(CreateView):
    pass
class BaseLoginView(LoginView):
    pass

class BaseDetailView(DetailView): 
    pass

class BaseRedirectView(RedirectView):
    pass

ecommerce/cart/views.py

# Create your views here.
from django.shortcuts import render,redirect
from django.views.generic import View
from base.views import BaseCreateView, BaseDeleteView, BaseListView,BaseUpdateView,BaseTemplateView
from cart.utils import tot_amount
from cart.models import Cart
from product.models import Product
from django.contrib import messages
from django.urls import reverse_lazy
from django.http import JsonResponse,HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from user.models import UserAddress
# Create your views here.

class AddToCart(LoginRequiredMixin,View):
    template_name='userportal/index.html'
    def post(self,request, *args, **kwargs):
        product_id=self.kwargs.get('productid')
        product=Product.objects.get(id=product_id)    
        qty =request.POST.get('qty')
        try:
            if qty:
                qty = eval(qty)
                cart, is_created = Cart.objects.get_or_create(user=self.request.user, product=product)
                if is_created:
                    cart.qty = qty
                else:
                    cart.qty += qty
                cart.save()
            else:
                Cart.objects.create(user=self.request.user, product=product)
            # messages.success(request, 'Add to cart successfully!')    
            
        except Exception:
            return HttpResponse("Exception: Data not found") 
        return JsonResponse(data={
                'message' : 'cart created successfully'
            })
class CartDeleteView(LoginRequiredMixin,View):
    model=Cart
    success_url=reverse_lazy('cart:list')
    
    def post(self, request, *args, **kwargs):        
        cart_id = kwargs.get("cart_item_id")
        try:
            cart=Cart.objects.get(id=cart_id)
            cart.delete()
            user=self.request.user
            grand_total = tot_amount(user) 
        except Exception:
             return HttpResponse("Exception: Data not found")  
        return JsonResponse(data={
                'message' : 'cart deleted successfully','grand_total':grand_total
            })

class CartQtyChangeView(LoginRequiredMixin,View):
    def post(self, request ,*args, **kwargs):
        product_id=request.POST.get('product_id')
        print(product_id)
        update_qty =request.POST.get('update_qty')
        print(update_qty)
        
        qty = eval(update_qty)
        print(type(qty))
        product=Product.objects.get(id=product_id) 
        cart=Cart.objects.get(user=self.request.user, product=product)
        cart.qty=qty
        cart.save()
        amount=cart.qty*product.price
        user=self.request.user
        grand_total = tot_amount(user) 
        return JsonResponse(data={'message' : 'cart  updated successfully','amount':amount,'grand_total':grand_total})

class CartListView(LoginRequiredMixin,BaseListView):
    template_name='userportal/cart.html'
    model=Cart
    def get(self,request):
        user=self.request.user
        cart_item=Cart.objects.filter(user=user)
        grand_total = tot_amount(user) 
        print('grand total',grand_total)
        return render(request,'userportal/cart.html',{'carts':cart_item,'grand_total':grand_total})
         

class CheckoutCart(BaseTemplateView):
    template_name='userportal/checkout.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart']= Cart.objects.filter(user=self.request.user) 
        context['user_addresses']=UserAddress.objects.filter(user=self.request.user)
        context['total'] =  tot_amount(user=self.request.user) 
        return context

ecommerce/templates/userportal/base.html
{% load static  %}

<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Favicon-->
	<link rel="shortcut icon" href={% static "userportal/img/fav.png"%}>
	<!-- Author Meta -->
	<meta name="author" content="CodePixar">
	<!-- Meta Description -->
	<meta name="description" content="">
	<!-- Meta Keyword -->
	<meta name="keywords" content="">
	<!-- meta character set -->
	<meta charset="UTF-8">
	<!-- Site Title -->
	<title>Karma Shop</title>
	<!--
		CSS
		============================================= -->
	<link rel="stylesheet" href={% static 'userportal/css/linearicons.css'%}>
	<link rel="stylesheet" href={% static 'userportal/css/font-awesome.min.css'%}>
	<link rel="stylesheet" href={% static "userportal/css/themify-icons.css"%}>
	<link rel="stylesheet" href={% static "userportal/css/bootstrap.css"%}>
	<link rel="stylesheet" href={% static "userportal/css/owl.carousel.css"%}>
	<link rel="stylesheet" href={% static "userportal/css/nice-select.css"%}>
	<link rel="stylesheet" href={% static "userportal/css/nouislider.min.css"%}>
	<link rel="stylesheet" href={% static "userportal/css/ion.rangeSlider.css" %}/>
	<link rel="stylesheet" href={% static "userportal/css/ion.rangeSlider.skinFlat.css" %}/>
	<link rel="stylesheet" href={% static "userportal/css/magnific-popup.css"%}>
	<link rel="stylesheet" href={% static "userportal/css/main.css"%}>
	{% block css %}
	  
	{% endblock css %}
</head>

<body>

	<!-- Start Header Area -->
	<header class="header_area sticky-header">
		<div class="main_menu">
			<nav class="navbar navbar-expand-lg navbar-light main_box">
				<div class="container">
					<!-- Brand and toggle get grouped for better mobile display -->
					<a class="navbar-brand logo_h" href="{% url 'user:dashboard' %}"><img src={% static "userportal/img/logo.png"%} alt=""></a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
					 aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse offset" id="navbarSupportedContent">
						<ul class="nav navbar-nav menu_nav ml-auto">

							<li class="nav-item active"><a class="nav-link" href="{% url 'user:dashboard' %}">Home</a></li>
							<li class="nav-item submenu dropdown">
								<a href="{% url 'user:category' %}" class="nav-link dropdown-toggle" >Category</a>
							</li>
								
						{% if user.is_authenticated %}
						
						<li class="nav-item active">
							<a href="{% url 'order:order_lists'   %}" class="nav-link dropdown-toggle" >Order</a>
						</li>
						{% if user.image %}
					
						<li class="nav-item active">
							<a href="{% url 'profile' user.pk  %}"><img src="{{user.image.url}}" width=50px  height=50px ></a>

						</li>
						{% else %}								  
						<li class="nav-item active">
							<a href="{% url 'user:profile' user.pk %}"><img src="{% static "userportal/img/r7.jpg" %}" width=50px  height=50px></a>
						</li>
						{% endif %}
						<li class="nav-item active"><a class="nav-link dropdown-toggle"  role="button" 
							aria-expanded="false" href="{% url 'logout' %}">Logout</a></li>
						{% else %}
						<li class="nav-item active"><a class="nav-link dropdown-toggle"  role="button"  href="{% url 'user:login' %}">Login</a></li>
						{% endif %}
					</li>
					</ul>
					<!-- <i class="bi bi-bookmark"></i> -->
						<ul class="nav navbar-nav navbar-right">
							<li class="nav-item"><a href="{% url 'user:wishlist' %}" class="wistlist"><span class="ti-bookmark"></span></a></li>
							<li class="nav-item"><a href="{% url 'cart:list' %}" class="cart"><span class="ti-bag"></span></a></li>
							<li class="nav-item">
								<button class="search"><span class="lnr lnr-magnifier" id="search"></span></button>
							</li>
						</ul>
					</div>
				</div>
			</nav>
		</div>
		<div class="main_menu" >
			<div class="container">
			{% block message %}
			  
			{% endblock message %}
			</div>
		</div>
		<div class="search_input" id="search_input_box">
			<div class="container">
				<form class="d-flex justify-content-between">
					<input type="text" class="form-control" id="search_input" placeholder="Search Here">
					<button type="submit" class="btn"></button>
					<span class="lnr lnr-cross" id="close_search" title="Close Search"></span>
				</form>
			</div>
		</div>

	</header>
	
<!-- End Header Area -->
{% block container %}

{% endblock container %}
<!-- start footer Area -->
<footer class="footer-area section_gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>About Us</h6>
                    <p style="color:aqua">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore
                        magna aliqua.
                    </p>
                </div>
            </div>
            <div class="col-lg-4  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Newsletter</h6>
                    <p style="color:aqua">Stay update with our latest</p>
                    <div class="" id="mc_embed_signup">

                        <form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                         method="get" class="form-inline">

                            <div class="d-flex flex-row">

                                <input class="form-control" name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '"
                                 required="" type="email">


                                <button class="click-btn btn btn-default"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></button>
                                <div style="position: absolute; left: -5000px;">
                                    <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                                </div>

                                <!-- <div class="col-lg-4 col-md-4">
                                            <button class="bb-btn btn"><span class="lnr lnr-arrow-right"></span></button>
                                        </div>  -->
                            </div>
                            <div class="info"></div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget mail-chimp">
                    <h6 class="mb-20">Instragram Feed</h6>
                    <ul class="instafeed d-flex flex-wrap">
                        <li><img src={% static "userportal/img/i1.jpg"%} alt=""></li>
                        <li><img src={% static "userportal/img/i2.jpg"%} alt=""></li> 
                        <li><img src={% static "userportal/img/i3.jpg"%} alt=""></li>
                        <li><img src={% static "userportal/img/i4.jpg"%} alt=""></li>
                        <li><img src={% static "userportal/img/i5.jpg"%} alt=""></li>
                        <li><img src={% static "userportal/img/i6.jpg"%} alt=""></li>
                        <li><img src={% static "userportal/img/i7.jpg"%} alt=""></li>
                        <li><img src={% static "userportal/img/i8.jpg"%} alt=""></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Follow Us</h6>
                    <p style="color:aqua">Let us be social</p>
                    <div class="footer-social d-flex align-items-center">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                        <a href="#"><i class="fa fa-behance"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom d-flex justify-content-center align-items-center flex-wrap">
            <p class="footer-text m-0" style="color:aqua"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
</p>
        </div>
    </div>
</footer>
<!-- End footer Area -->


<script src={% static "userportal/js/vendor/jquery-2.2.4.min.js"%}></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
 crossorigin="anonymous"></script>
<script src={% static "userportal/js/vendor/bootstrap.min.js"%}></script>
<script src={% static "userportal/js/jquery.ajaxchimp.min.js"%}></script>
<script src={% static "userportal/js/jquery.nice-select.min.js"%}></script>
<script src={% static "userportal/js/jquery.sticky.js"%}></script>
<script src={% static "userportal/js/nouislider.min.js"%}></script>
<!-- <script src={% static "userportal/js/countdown.js"%}></script> -->
<script src={% static "userportal/js/jquery.magnific-popup.min.js"%}></script>
<script src={% static "userportal/js/owl.carousel.min.js"%}></script>
<!--gmaps Js-->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
<script src={% static "userportal/js/gmaps.min.js"%}></script>
<script src={% static "userportal/js/main.js"%}></script>
{% block javascript %}

{% endblock javascript %}

</body>

</html>

ecommerce/templates/userportal/cart.html
{% extends "userportal/base.html" %} {% block container %} {% load static %} 
{% load mathfilters %}
<!-- Start Banner Area -->

<section class="banner-area organic-breadcrumb">
  <div class="container">
    <div
      class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end"
    >
      <div class="col-first">
        <h1>Shopping Cart</h1>
        <nav class="d-flex align-items-center">
          <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
          <a href="category.html">Cart</a>
        </nav>
      </div>
    </div>
  </div>
</section>
<!-- End Banner Area -->
<!--================Cart Area =================-->
{% comment %}
<form method="get" id="form-tmp">
  {% endcomment %} {% csrf_token %}
  <section class="cart_area">
    <div class="container">
      <div class="cart_inner">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Product</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
                <th scope="col">Total</th>
              </tr>
            </thead>
            <tbody>
              {% for cart in carts %}
              <tr id="delete_{{cart.id}}">
                <td>
                  <div class="media">
                    <div class="d-flex">
                      <img
                        src="{{cart.product.images.all.first}}"
                        width="50px"
                        alt=""
                      />
                    </div>
                    <div class="media-body">
                      <p>{{cart.product}}</p>
                    </div>
                  </div>
                </td>
                <td>
                  <h5 >RS.{{cart.product.price}}</h5>
                </td>
                <td>
                  <div class="product_count">
                    <input
                      type="number"
                      name="qty"
                      id="qty_{{cart.product.id}}"
                      min=1
                      maxlength="12"
                      value="{{cart.qty}}"
                      title="Quantity:"
                      class="input-text qty"
                      data-product-id="{{cart.product.id}}"
                    />
                   
                    {% comment %} <button
                      onclick="var result = document.getElementById('{{cart.product}}');
                       var sst = result.value; if( !isNaN( sst )) result.value++;return false;"
                      class="increase items-count"
                      type="button"
                    >
                      <i class="lnr lnr-chevron-up"></i>
                    </button>
                    <button
                      onclick="var result = document.getElementById('{{cart.product}}');
                       var sst = result.value; if( !isNaN( sst ) &amp;\amp; sst > 0 ) result.value--;return false;"
                      class="reduced items-count"
                      type="button"
                    >
                      <i class="lnr lnr-chevron-down"></i></button
                    > {% endcomment %}
                  </div>
                </td>
                <td><h5 id="total_{{cart.product.id}}">RS.{{cart.product.price|mul:cart.qty}}</h5>
                </td>
                <td>
                  <button
                    class="fa fa-trash-o"
                    id="delete_cart_{{cart.id}}"
                    name="delete_cart"
                    style="font-size: 36px; color: red"
                    data-cartid="{{cart.id}}"
                  ></button>
                </td>
              </tr>
              {% endfor %}

              <tr class="bottom_button">
                <td>
                  
                </td>
                <td></td>
                <td></td>
                <td>
                  
                </td>
              </tr>
              <tr>
                <td></td>
                <td></td>
                <td>
                  <h5>Subtotal</h5>
                </td>
                <td>
                  <h5 id="grand_total" >RS.{{grand_total}}</h5>
                </td>
              </tr>
              <tr class="out_button_area">
                <td></td>
                <td></td>
                <td></td>
                <td>
                  <div class="checkout_btn_inner d-flex align-items-center">
                    <a class="gray_btn" href="{% url 'user:dashboard' %}"
                      >Continue Shopping</a
                    >
                    <a class="primary-btn" href="{% url 'cart:checkout' %}"
                      >Proceed to checkout</a
                    >
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </section>
  {% comment %}
</form>
{% endcomment %}
<!--================End Cart Area =================-->
{% endblock %} {% block javascript %}
<script type="text/javascript">
  console.log("jqury");
  $(".fa-trash-o").click(function () {
    cart_item_id = $(this).data("cartid");

    $.ajax({
      url: `{% url 'cart:delete_cart' '0' %}`.replace("0", cart_item_id),
      type: "post",
      data: { csrfmiddlewaretoken: "{{csrf_token}}" },
      success: function (response) {
        console.log(response);
        console.log(cart_item_id);
        $('#delete_'+cart_item_id).remove(); 
        var total = 'RS.'+response.grand_total;
        console.log('>>>>>>>>>>>',total); 
        $('#grand_total').text(total); 
      },
    });
  });
</script>

<script type="text/javascript">
  $(".qty").change(function () {
      console.log(">>>>>>>>>>>>>>>>>>>>>>>>>>>")
      product_id = $(this).data('product-id') 
       update_qty=$('#qty_'+product_id).val()
       console.log(product_id);
       console.log(update_qty);
       $.ajax({
          url:`{% url 'cart:update_cart' %}`,
          type:'POST',
          data:{
              csrfmiddlewaretoken: "{{csrf_token}}",
                  'update_qty':update_qty,
                  'product_id':product_id,
              },
          success: function (response) {
            console.log(response);
            var total = 'RS.'+response.amount; 
            var grand_total = 'RS.'+response.grand_total
            console.log(grand_total);
            $('#grand_total').text(grand_total);
            $('#total_'+product_id).text(total);
          },
      });
  });
</script>

{% endblock javascript %} 

ecommerce/templates/userportal/checkout.html
{% extends "userportal/base.html" %}
{% block container %}
 {% load static %} 
 {% load mathfilters %}
    <!-- Start Banner Area -->
    <section class="banner-area organic-breadcrumb">
        <div class="container">
            <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
                <div class="col-first">
                    <h1>Checkout</h1>
                    <nav class="d-flex align-items-center">
                        <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
                        <a href="single-product.html">Checkout</a>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- End Banner Area -->

    <!--================Checkout Area =================-->
    <section class="checkout_area section_gap">
        <div class="container">
            <form action="/order/placeorder" method="GET">
                <div class="billing_details">
                    <div class="row">
                        <div class="col-lg-8">
                            <h3>Billing Details</h3>
                            {% comment %} address card {% endcomment %}
                            <a href="{% url 'user:create_address' %}" ><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-plus" viewBox="0 0 16 16">
                                <path d="M8.5 6a.5.5 0 0 0-1 0v1.5H6a.5.5 0 0 0 0 1h1.5V10a.5.5 0 0 0 1 0V8.5H10a.5.5 0 0 0 0-1H8.5V6z"/>
                                <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm10-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1z"/>
                              </svg>Add address</a>
                            <div class="row">
                                {% for address in user_addresses %}
                                <div class="col-sm-6">
                                        <div class="card">
                                            <div class="card-body">
                                                <div class="custom-control custom-radio">
                                                    <input type="radio" id="customRadio{{forloop.counter}}" name="custid" class="custom-control-input" value="{{address.id}}" required="" placeholder="username"
                                                    oninvalid="this.setCustomValidity('Please select any address')"
                                                    oninput="setCustomValidity('')">
                                                    <label class="custom-control-label" for="customRadio{{forloop.counter}}">
                                                        <h5 class="card-title">Address {{forloop.counter}}</h5>
                                                    </label>
                                                  </div>
                                            <p class="card-text">{{address.address}}</p>
                                            <p class="card-text">{{address.city}}, {{address.state}} {{address.country}} {{address.zip_code}} </p>
                                            
                                             <a href="{% url 'user:address_update' address.pk %}" class="btn fa fa-edit  btn-outline-info ">Edit</a>
                                            <form action="{% url 'user:address_delete' address.pk %}" method="POST" class="d-inline" >
                                                {% csrf_token %}
                                            <button type="submit" class="btn btn-outline-danger">Delete</button>
                                            </form> 
                                            </div>
                                        </div>
                                </div>
                                {% endfor %}
                            
                              </div>
                            </div>

                        <div class="col-lg-4">
                            <div class="order_box">
                                
                                <h2>Your Order</h2>
                                <ul class="list">
                                    <li><a disabled="disabled">Product <span>Total</span></a></li>
                                    {% for carts in cart %}
                                    
                                <li><a href="{% url 'product:product_details' carts.product.pk  %}">{{carts.product|truncatechars:10}}
                                <span class="middle"></span>x{{carts.qty}}<span class="last">
                                    ${{carts.product.price}}</span></a></li>
                                {% endfor %}
                                </ul>    
                                <ul class="list list_2">
                                    
                                    <li><a  disabled="disabled">Total<span>RS.{{total}}</span></a></li>
                                </ul>

                                </div>
                                <button type="submit" class="primary-btn">Placed Order</button>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </form>    
        </div>
    </section>
    <!--================End Checkout Area =================-->

    {% endblock %}
{% block javascript %}
<script>
$(document).ready(function(){
  $(".primary-btn").click(function(){
    alert("The paragraph was clicked.");
  });
});


    
</script>
{% endblock javascript %}